# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:labctl:
    internal: false
    env:
      CGO_ENABLED: 1
      CC: clang
      CXX: clang++
    sources:
      - "./**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "./bin/labctl"
    cmds:
      - go build -o ./bin/labctl ./cmd/labctl

  setup:incus:check:
    desc: "Print report of found/missing incus variables"
    deps: [build:labctl]
    cmds:
      - ./bin/labctl check incus ansible:inventory:add ansible:playbook:run ssh:add
    run: once

  setup:incus:
    desc: >
      This task configures proxmox after booting it for the first time.
      It also creates some firewall rules and security groups.
    deps: [build:labctl]
    cmds:
      - ./bin/labctl ansible galaxy install requirements
      - ./bin/labctl ansible inventory add incus
      - ./bin/labctl ansible playbook run incus
      - ./bin/labctl ssh add incus
      - incus remote add my-homelab
      - incus remote switch my-homelab
      - incus list # verify

  setup:plex:check:
    desc: "Print report of found/missing plex variables"
    deps: [build:labctl]
    cmds:
      - ./bin/labctl check plex terraform:apply ssh:add ansible:playbook:run
    run: once

  setup:plex:
    desc: This task provisions and configures a plex LXC
    deps: [build:labctl]

    cmds:
      - ./bin/labctl terraform apply plex
      - ./bin/labctl ssh add plex
      - ./bin/labctl ansible playbook run plex
