# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:labctl:
    internal: false
    env:
      CGO_ENABLED: 1
      CC: clang
      CXX: clang++
    sources:
      - "./**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "./bin/labctl"
    cmds:
      - go build -o ./bin/labctl ./cmd/labctl

  setup:
    internal: true
    deps: [build:labctl]
    cmds:
      # for host in hosts {
      #   ./bin/labctl ansible inventory add {{.HOST}} # creates inventory file with host and also the VMs of this host. if an inventory file already exists, it will override it
      #   ./bin/labctl ansible playbook run bootstrap-host.yml --limit {{.HOST}} -u root
      #   ./bin/labctl ansible playbook run setup-host.yml --limit {{.HOST}}
      #   ./bin/labctl ssh add {{.HOST}}
      #   ./bin/labctl terrafom apply VM # creates one or more VMs (depending on what is in config) each VM will get an IP which is defined in config
      #   ./bin/labctl ansible playbook run bootstrap-host.yml --limit vms -u root
      #   for vm in host.vms {
      #     ./bin/labctl ssh add vm
      #   }
      #   if existing incus cluster {
      #     ./bin/labctl incus cluster join {{.HOST}}
      #   } else {
      #     incus remote add my-homelab
      #     incus remote switch my-homelab
      #   }
      # }
      # incus list
      - ./bin/labctl setup {{if .HOST}}--host {{.HOST}}{{end}}

  setup:check:
    desc: Validate config for setup (all hosts, or one with HOST=<name>)
    cmds:
      - ./bin/labctl setup --check {{if .HOST}}--host {{.HOST}}{{end}}

  # setup:remote_server:check:
  #   desc: "Print report of found/missing variables for setup:remote_server command"
  #   deps: [build:labctl]
  #   vars:
  #     HOST: "{{.HOST}}"
  #   preconditions:
  #     - sh: 'test -n "{{.HOST}}"'
  #       msg: "Error: 'HOST' variable is required. Run with 'task setup:remote_server:check HOST=your_host'"
  #   cmds:
  #     - ./bin/labctl check {{.HOST}} ansible:inventory:add ansible:playbook:run ssh:add
  #   run: once

  # setup:remote_server:
  #   desc: "Configures a remote server. Usage: task setup:remote_server HOST=my-server"
  #   deps: [build:labctl]
  #   vars:
  #     HOST: "{{.HOST}}"
  #   preconditions:
  #     - sh: 'test -n "{{.HOST}}"'
  #       msg: "Error: 'HOST' variable is required. Run with 'task setup:remote_server HOST=your_host'"
  #   cmds:
  #     # adds to [remote_vps] group
  #     - ./bin/labctl ansible inventory add {{.HOST}}

  #     # run ansible-playbook bootstrap-host.yml --limit $host -u root
  #     # run ansible-playbook setup-remote.yml
  #     - ./bin/labctl ansible playbook run {{.HOST}}

  #     - ./bin/labctl ssh add {{.HOST}}
