# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:labctl:
    internal: false
    env:
      CGO_ENABLED: 1
      CC: clang
      CXX: clang++
    sources:
      - "./**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "./bin/labctl"
    cmds:
      - go build -o ./bin/labctl ./cmd/labctl

  setup:proxmox:check:
    desc: "Print report of found/missing proxmox variables"
    deps: [build:labctl]
    cmds:
      - ./bin/labctl check proxmox ansible:playbook:run ssh:add
    run: once

  setup:proxmox:
    desc: This task sets up proxmox after booting it for the first time.
    deps: [build:labctl]

    cmds:
      - ./bin/labctl ansible playbook run proxmox
      - ./bin/labctl ssh add proxmox
      - ./bin/labctl terraform apply proxmox

  setup:plex:check:
    desc: "Print report of found/missing plex variables"
    deps: [build:labctl]
    cmds:
      - ./bin/labctl check plex terraform:apply
    run: once

  setup:plex:
    desc: This task sets up plex after booting it for the first time.
    deps: [build:labctl]

    cmds:
      - ./bin/labctl terraform apply plex
      #- ./bin/labctl ssh add plex
      #- ./bin/labctl ansible playbook run plex
