- name: Install Incus (and dependencies)
  ansible.builtin.apt:
    name:
      - incus
      - incus-tools
    state: present
    update_cache: yes

- name: Ensure 'incus-admin' group exists
  ansible.builtin.group:
    name: incus-admin
    state: present

- name: Add admin user to incus-admin group
  ansible.builtin.user:
    name: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    groups: incus-admin
    append: yes

- name: Ensure Incus service is started and enabled
  ansible.builtin.service:
    name: incus
    state: started
    enabled: yes


- name: Allow Incus API (8443)
  community.general.ufw:
    rule: allow
    port: "8443"
    proto: tcp
    comment: "Remote Terraform Access"

- name: Allow Traffic on Incus Bridge (DNS/DHCP)
  community.general.ufw:
    rule: allow
    direction: in
    interface: incusbr0
    comment: "Allow container traffic to host (DNS/DHCP)"

- name: Block Incus Subnet from accessing LAN (Egress Filtering)
  community.general.ufw:
    rule: deny
    route: yes
    from_ip: "10.0.100.0/24"
    to_ip: "10.0.0.0/24"
    comment: "Block Incus -> LAN"
