- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow custom SSH port
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Enable UFW with default deny incoming
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow all outgoing traffic
  community.general.ufw:
    policy: allow
    direction: outgoing
