ssh_user: "admin"
ssh_port: 17031
ssh_private_key_path: "~/.ssh/id_ed25519"
ssh_public_key_path: "~/.ssh/id_ed25519.pub"
gateway_address: 10.0.0.1
physical_nic: "enx6c1ff7135975"
auto_update_reboot_time: "05:00"
