### Create admin
- name: Create admin user with a password
  ansible.builtin.user:
    name: admin
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present
    # Hash the plain-text password from the prompt
    password: "{{ vault_admin_password | password_hash('sha512') }}"
    update_password: on_create # only sets it if the user is new

- name: Allow admin user sudo access (requires password)
  ansible.builtin.copy:
    dest: /etc/sudoers.d/admin
    content: "admin ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0440"

- name: Set up SSH for admin
  ansible.builtin.authorized_key:
    user: admin
    state: present
    key: "{{ ssh_public_key }}"

### Harden SSH
- name: Configure SSH hardening
  ansible.builtin.blockinfile:
    path: "/etc/ssh/sshd_config.d/00-user.conf"
    create: true
    marker: "# {mark} ANSIBLE MANAGED SSH CONFIG"
    block: |
      Port {{ ssh_port }}
      PasswordAuthentication no
      PermitRootLogin no
  register: ssh_config

- name: Allow custom SSH port in ufw
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Set default policy to deny all incoming traffic
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Set default policy to allow all outgoing traffic
  community.general.ufw:
    policy: allow
    direction: outgoing

- name: Disable port 22
  community.general.ufw:
    rule: deny
    port: "22"
    proto: tcp

- name: Restart sshd immediately
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: ssh_config.changed
