---
- name: Harden SSH, setup terraform and tailscale
  hosts: proxmox
  become: true
  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  vars_files:
    - /var/homelab.yml

  tasks:
    - name: Configure SSH hardening
      become: yes
      ansible.builtin.blockinfile:
        path: "/etc/ssh/sshd_config.d/00-user.conf"
        create: true
        marker: "# {mark} ANSIBLE MANAGED SSH CONFIG"
        block: |
          Port {{ ssh_port }}
          PasswordAuthentication no
          PermitRootLogin no
      notify: restart sshd

    - name: Create local terraform user
      user:
        name: terraform
        state: present

    - name: Set up SSH for terraform user
      authorized_key:
        user: terraform
        state: present
        key: "{{ ssh_public_key }}"

    - name: Set up sudo permissions for terraform
      copy:
        dest: /etc/sudoers.d/terraform
        content: |
          terraform ALL=(root) NOPASSWD: /sbin/pvesm
          terraform ALL=(root) NOPASSWD: /sbin/qm
          terraform ALL=(root) NOPASSWD: /usr/bin/tee /var/lib/vz/*
        mode: "0440"
        validate: /usr/sbin/visudo -cf %s

    - name: Create terraform user in Proxmox
      shell: pveum user add terraform@pve
      register: terraform_user_result
      failed_when: terraform_user_result.rc != 0 and 'already exists' not in terraform_user_result.stderr
      changed_when: terraform_user_result.rc == 0

    - name: Create Terraform role
      shell: >
        pveum role add Terraform -privs "Realm.AllocateUser, VM.PowerMgmt, VM.GuestAgent.Unrestricted,
        Sys.Console, Sys.Audit, Sys.AccessNetwork, VM.Config.Cloudinit, VM.Replicate, Pool.Allocate,
        SDN.Audit, Realm.Allocate, SDN.Use, Mapping.Modify, VM.Config.Memory, VM.GuestAgent.FileSystemMgmt,
        VM.Allocate, SDN.Allocate, VM.Console, VM.Clone, VM.Backup, Datastore.AllocateTemplate,
        VM.Snapshot, VM.Config.Network, Sys.Incoming, Sys.Modify, VM.Snapshot.Rollback, VM.Config.Disk,
        Datastore.Allocate, VM.Config.CPU, VM.Config.CDROM, Group.Allocate, Datastore.Audit, VM.Migrate,
        VM.GuestAgent.FileWrite, Mapping.Use, Datastore.AllocateSpace, Sys.Syslog, VM.Config.Options,
        Pool.Audit, User.Modify, VM.Config.HWType, VM.Audit, Sys.PowerMgmt, VM.GuestAgent.Audit,
        Mapping.Audit, VM.GuestAgent.FileRead, Permissions.Modify"
      register: terraform_role_result
      failed_when: terraform_role_result.rc != 0 and 'already exists' not in terraform_role_result.stderr
      changed_when: terraform_role_result.rc == 0

    - name: Assign role to terraform user
      command: pveum aclmod / -user terraform@pve -role Terraform
      register: role_assign_result
      failed_when: role_assign_result.rc != 0
      changed_when: false

    - name: Create Terraform API token
      command: pveum user token add terraform@pve provider --privsep=0
      register: token_output
      failed_when: token_output.rc != 0 and 'Token already exists' not in token_output.stderr
      changed_when: token_output.rc == 0

    - name: Display Terraform API token
      debug:
        msg: |
          ===============================
          SAVE THIS TERRAFORM API TOKEN:
          {{ token_output.stdout }}
          ===============================
      when: token_output.rc == 0

    - name: enable no-subscription repo
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/pve-no-subscription.sources
        create: true
        block: |
          Types: deb
          URIs: http://download.proxmox.com/debian/pve
          Suites: trixie
          Components: pve-no-subscription
          Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg

    - name: delete enterprise repo
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.sources
        state: absent

    - name: delete ceph enterprise repo
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/ceph.sources
        state: absent

    - name: create no-subscription ceph repo
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/ceph.sources
        block: |
          Types: deb
          URIs: http://download.proxmox.com/debian/ceph-squid
          Suites: trixie
          Components: no-subscription
          Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
        create: yes
        owner: root
        group: root
        mode: "0644"
      notify:
        - apt update

    - name: Add tailscale key and repository
      ansible.builtin.deb822_repository:
        name: tailscale
        types: [deb]
        uris: "https://pkgs.tailscale.com/stable/debian"
        suites: [trixie]
        components: [main]
        signed_by: https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg
        state: present
        enabled: true

    - name: Install tailscale
      apt:
        name:
          - tailscale
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Start Tailscale
      shell: tailscale up --authkey={{ tailscale_key }}
      args:
        creates: /var/lib/tailscale/tailscaled.state
      when: tailscale_key is defined

    # this is the directory that will be used as a mount point for VMs
    - name: Create media directory
      file:
        path: /mnt/media
        state: directory
        mode: "0755"

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
