[proxmox]
proxmox_server ansible_host=10.0.0.50

[wireguard]
wireguard-vm ansible_host=10.0.0.84

[plex]
plex_lxc ansible_host=10.0.0.85 vmid=100

[remote_vps]
vpn ansible_host=216.238.83.24
parkspot ansible_host=45.32.165.56

[all:vars]
ansible_python_interpreter=/usr/bin/python3
