[proxmox]
proxmox_server ansible_host=100.102.23.84

[vm_group]
vm ansible_host=10.0.0.84 ansible_user=ubuntu

[plex]
plex_lxc ansible_host=10.0.0.85

[remote_vps]
vpn ansible_host=216.238.83.24

[all:vars]
ansible_python_interpreter=/usr/bin/python3
