---
- name: Prepare server by hardening SSH and automating updates
  hosts: remote_vps
  become: true
  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  roles:
    - ssh_harden
    - automated_updates
